import { defineConfig, presetUno, presetAttributify, presetIcons, presetTypography } from 'unocss';

export default defineConfig({
	presets: [presetUno(), presetAttributify(), presetIcons(), presetTypography()],
	theme: {
		colors: {
			slate: {
				100: '#f1f5f9',
				200: '#e2e8f0',
				300: '#cbd5e1',
				400: '#94a3b8',
				500: '#64748b',
				600: '#475569',
				700: '#334155',
				800: '#1e293b',
				900: '#0f172a'
			}
		}
	},
	shortcuts: {
		btn: 'px-4 py-2 rounded-lg font-medium transition-colors duration-200',
		'btn-primary': 'bg-blue-500 text-white hover:bg-blue-600',
		'btn-secondary': 'bg-gray-100 text-gray-700 hover:bg-gray-200'
	},
	safelist: [
		'bg-gray-800',
		'bg-gray-700',
		'bg-gray-600',
		'text-gray-400',
		'text-gray-300',
		'text-gray-500',
		'border-gray-700',
		'border-gray-600',
		'from-blue-400',
		'to-violet-400',
		'from-blue-500',
		'to-violet-500',
		'bg-gradient-to-r',
		'bg-gradient-to-br',
		'backdrop-blur-sm',
		'bg-gray-800/50',
		'bg-gray-700/50',
		'hover:bg-gray-700',
		'hover:text-white',
		'group-hover:rotate-180',
		'transition-all',
		'transition-colors',
		'transition-transform',
		'duration-200',
		'duration-500',
		'min-h-screen',
		'mx-auto',
		'max-w-7xl',
		'max-w-3xl',
		'px-4',
		'py-6',
		'py-8',
		'sm:px-6',
		'lg:px-8',
		'flex',
		'items-center',
		'justify-between',
		'gap-2',
		'gap-3',
		'gap-4',
		'gap-6',
		'text-sm',
		'text-3xl',
		'font-medium',
		'font-bold',
		'tracking-tight',
		'text-transparent',
		'bg-clip-text',
		'mt-2',
		'h-2',
		'h-4',
		'h-5',
		'w-4',
		'w-5',
		'flex-1',
		'overflow-hidden',
		'rounded-full',
		'rounded-lg',
		'rounded-xl',
		'rounded-2xl',
		'shadow-lg',
		'shadow-2xl',
		'ring-1',
		'ring-gray-700',
		'disabled:opacity-50',
		'disabled:hover:bg-gray-700/50',
		'disabled:hover:text-gray-300',
		'sm:w-auto',
		'sm:flex-none',
		'sm:flex-row',
		'md:p-6',
		'space-y-4',
		'leading-relaxed'
	]
});
